name: 刷步数

on:
  schedule:
    - cron: '41 1,4,7,9 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
      - name: Update system and install zsh
        run: |
          sudo dnf -y update
          sudo dnf -y install zsh
          
      - name: 开始
        env:
            CONFIG: ${{ secrets.CONFIG }}
        run: |
          pip3 install requests pytz
          python3 main.py

      - name: Send Bark Notification
        env:
          BARK_SERVER_URL: ${{ secrets.BARK_SERVER_URL }}
          BARK_KEY: ${{ secrets.BARK_KEY }}
        run: |
          TITLE="Xiao Mi Step Done"
          # 构建完整 URL 并发送请求
          curl -X GET "${BARK_SERVER_URL}/${BARK_KEY}/${TITLE}"
